import type { Response } from "express";
import { User } from "../models/User.js";
import { Portfolio } from "../models/Portfolio.js";
import type { AuthRequest } from "../middleware/auth.js";

function publicUser(user:any){return {id:user._id,name:user.name,email:user.email,role:user.role,headline:user.headline,bio:user.bio,location:user.location,skills:user.skills,languages:user.languages,avatar:user.avatar,rating:user.rating,completedProjects:user.completedProjects,createdAt:user.createdAt};}
export async function getMyProfile(req:AuthRequest,res:Response){if(!req.user)return res.status(401).json({message:"Authentication required."});const user=await User.findById(req.user.id);if(!user)return res.status(404).json({message:"User not found."});const portfolio=await Portfolio.find({freelancerId:user._id}).sort({createdAt:-1});return res.json({user:publicUser(user),portfolio});}
export async function updateMyProfile(req:AuthRequest,res:Response){if(!req.user)return res.status(401).json({message:"Authentication required."});const user=await User.findById(req.user.id);if(!user)return res.status(404).json({message:"User not found."});for(const key of ["name","headline","bio","location","skills","languages","avatar",
    "hourlyRate",
    "availability"]){if(req.body[key]!==undefined){if(["skills","languages"].includes(key)&&!Array.isArray(req.body[key]))return res.status(400).json({message:`${key} must be an array.`});(user as any)[key]=req.body[key];}}await user.save();return res.json({user:publicUser(user)});}
export async function getFreelancers(req:AuthRequest,res:Response){const {search="",skill,location}=req.query;const filter:any={role:"freelancer"};if(skill&&skill!=="All")filter.skills={$in:[String(skill)]};if(location&&location!=="All")filter.location=String(location);if(String(search).trim()){const q=String(search).trim();filter.$or=[{name:{$regex:q,$options:"i"}},{headline:{$regex:q,$options:"i"}},{bio:{$regex:q,$options:"i"}},{skills:{$regex:q,$options:"i"}}];}const freelancers=await User.find(filter).select("name headline bio location skills languages avatar rating completedProjects hourlyRate availability createdAt").sort({rating:-1,completedProjects:-1}).limit(100);return res.json({freelancers});}
export async function getFreelancer(req:AuthRequest,res:Response){const user=await User.findOne({_id:req.params.id,role:"freelancer"}).select("name headline bio location skills languages avatar rating completedProjects hourlyRate availability createdAt");if(!user)return res.status(404).json({message:"Freelancer not found."});const portfolio=await Portfolio.find({freelancerId:user._id}).sort({createdAt:-1});return res.json({user,portfolio});}
