"use client";
import { FormEvent, useEffect, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import AppShell from "@/components/AppShell";
import { api } from "@/lib/api";

type Project={_id:string;totalAmount:number;status:string;escrowStatus:string;jobId:{title:string;company:string;category:string;description:string;skills:string[]};freelancerId:{_id:string;name:string;headline?:string;rating:number};employerId:{_id:string;name:string}};
type Milestone={_id:string;title:string;description:string;amount:number;status:string;deliverable?:string;dueDate?:string};
type Review={_id:string;rating:number;comment:string;reviewerId:{name:string}};
export default function ProjectPage(){
 const {id}=useParams<{id:string}>(); const [project,setProject]=useState<Project|null>(null); const [milestones,setMilestones]=useState<Milestone[]>([]); const [reviews,setReviews]=useState<Review[]>([]); const [message,setMessage]=useState(""); const [deliverable,setDeliverable]=useState(""); const [review,setReview]=useState({rating:"5",comment:""}); const [milestoneForm,setMilestoneForm]=useState({title:"",description:"",amount:""});
 async function load(){const [p,m,r]=await Promise.all([api<{project:Project}>(`/projects/${id}`),api<{milestones:Milestone[];transactions:any[]}>(`/milestones/project/${id}`),api<{reviews:Review[]}>(`/reviews/project/${id}`)]);setProject(p.project);setMilestones(m.milestones);setReviews(r.reviews)} useEffect(()=>{load()},[id]);
 async function fund(){await api(`/projects/${id}`,{method:"PATCH",json:{status:"in-progress",escrowStatus:"funded"}});setMessage("Project funded and started.");load()}
 async function addMilestone(e:FormEvent){e.preventDefault();await api(`/milestones/project/${id}`,{method:"POST",json:{...milestoneForm,amount:Number(milestoneForm.amount)}});setMilestoneForm({title:"",description:"",amount:""});load()}
 async function submitMilestone(mid:string){await api(`/milestones/${mid}/submit`,{method:"PATCH",json:{deliverable}});setDeliverable("");load()}
 async function milestoneAction(mid:string,status:string){await api(`/milestones/${mid}`,{method:"PATCH",json:{status}});load()}
 async function complete(){await api(`/projects/${id}`,{method:"PATCH",json:{status:"completed",escrowStatus:"released"}});load()}
 async function addReview(e:FormEvent){e.preventDefault();await api(`/reviews/project/${id}`,{method:"POST",json:{rating:Number(review.rating),comment:review.comment}});setReview({rating:"5",comment:""});setMessage("Review submitted.");load()}
 if(!project)return <main className="min-h-screen bg-[#0a0a0b]"/>;
 return <AppShell><Link href="/projects" className="text-sm text-white/35 hover:text-white">← Back to projects</Link><div className="mt-7 grid gap-6 xl:grid-cols-[1fr_330px]">
  <section className="space-y-5">
   <div className="rounded-2xl border border-white/[0.08] bg-white/[0.025] p-6 sm:p-8"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-indigo-400/[0.08] px-2.5 py-1 text-xs text-indigo-300">{project.jobId.category}</span><span className="rounded-full bg-emerald-400/[0.08] px-2.5 py-1 text-xs capitalize text-emerald-300">{project.status}</span></div><h1 className="mt-4 text-3xl font-semibold tracking-tight">{project.jobId.title}</h1><p className="mt-2 text-sm text-white/35">{project.jobId.company}</p><div className="mt-8 grid gap-3 sm:grid-cols-2"><div className="rounded-xl bg-white/[0.035] p-4"><p className="text-xs text-white/30">Freelancer</p><p className="mt-2 text-sm font-medium">{project.freelancerId.name}</p></div><div className="rounded-xl bg-white/[0.035] p-4"><p className="text-xs text-white/30">Employer</p><p className="mt-2 text-sm font-medium">{project.employerId.name}</p></div></div></div>
   <div className="rounded-2xl border border-white/[0.08] bg-white/[0.025] p-6"><div className="flex items-end justify-between"><div><p className="text-xs uppercase tracking-[0.16em] text-indigo-300">Milestones</p><h2 className="mt-1 text-xl font-medium">Delivery plan</h2></div><span className="text-xs text-white/25">{milestones.length} milestones</span></div><div className="mt-6 space-y-3">{milestones.map(m=><div key={m._id} className="rounded-xl border border-white/[0.07] p-4"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><p className="font-medium">{m.title}</p><p className="mt-1 text-xs text-white/30">{m.description}</p></div><p className="text-sm font-semibold">₹{m.amount.toLocaleString("en-IN")}</p></div><div className="mt-4 flex items-center justify-between"><span className="rounded-full bg-white/[0.05] px-2.5 py-1 text-[10px] capitalize text-white/50">{m.status}</span>{m.status==="submitted"&&<button onClick={()=>milestoneAction(m._id,"approved")} className="rounded-lg bg-white px-3 py-2 text-[11px] font-semibold text-black">Approve & release</button>}{m.status==="submitted"&&<button onClick={()=>milestoneAction(m._id,"revision")} className="rounded-lg border border-white/[0.08] px-3 py-2 text-[11px] text-white/50">Request revision</button>}</div>{m.deliverable&&<p className="mt-3 text-xs text-white/40">Deliverable: {m.deliverable}</p>}{(m.status==="pending"||m.status==="revision"||m.status==="in-progress")&&<div className="mt-4 flex gap-2"><input value={m.status==="pending"?"":deliverable} onChange={e=>setDeliverable(e.target.value)} placeholder="Deliverable link / notes" className="h-10 flex-1 rounded-lg border border-white/[0.08] bg-black/20 px-3 text-xs"/><button onClick={()=>submitMilestone(m._id)} className="rounded-lg bg-indigo-400 px-3 py-2 text-[11px] font-semibold text-black">Submit</button></div>}</div>)}</div></div>
   <div className="rounded-2xl border border-white/[0.08] bg-white/[0.025] p-6"><p className="text-xs uppercase tracking-[0.16em] text-indigo-300">Employer setup</p><h2 className="mt-1 text-lg font-medium">Add a milestone</h2><form onSubmit={addMilestone} className="mt-4 grid gap-3 sm:grid-cols-3"><input required value={milestoneForm.title} onChange={e=>setMilestoneForm({...milestoneForm,title:e.target.value})} placeholder="Milestone title" className="h-10 rounded-lg border border-white/[0.08] bg-black/20 px-3 text-xs"/><input required value={milestoneForm.description} onChange={e=>setMilestoneForm({...milestoneForm,description:e.target.value})} placeholder="Description" className="h-10 rounded-lg border border-white/[0.08] bg-black/20 px-3 text-xs"/><input required type="number" min="1" value={milestoneForm.amount} onChange={e=>setMilestoneForm({...milestoneForm,amount:e.target.value})} placeholder="Amount ₹" className="h-10 rounded-lg border border-white/[0.08] bg-black/20 px-3 text-xs"/><button className="rounded-lg bg-white py-2 text-xs font-semibold text-black sm:col-span-3">Add milestone</button></form></div>
   <div className="rounded-2xl border border-white/[0.08] bg-white/[0.025] p-6"><p className="text-xs uppercase tracking-[0.16em] text-indigo-300">Reviews</p><h2 className="mt-1 text-lg font-medium">Project reputation</h2>{reviews.length===0?<p className="mt-4 text-sm text-white/30">Reviews appear after completion.</p>:<div className="mt-4 space-y-3">{reviews.map(r=><div key={r._id} className="rounded-xl bg-white/[0.035] p-4"><p className="text-sm">★ {r.rating} · {r.reviewerId.name}</p><p className="mt-2 text-sm text-white/40">{r.comment}</p></div>)}</div>}<form onSubmit={addReview} className="mt-5 space-y-3"><select value={review.rating} onChange={e=>setReview({...review,rating:e.target.value})} className="h-10 rounded-lg border border-white/[0.08] bg-[#111113] px-3 text-xs"><option>5</option><option>4</option><option>3</option><option>2</option><option>1</option></select><textarea required value={review.comment} onChange={e=>setReview({...review,comment:e.target.value})} placeholder="Leave a review after completion..." className="min-h-24 w-full rounded-lg border border-white/[0.08] bg-black/20 p-3 text-xs"/><button className="rounded-lg border border-white/[0.08] px-4 py-2 text-xs text-white/60">Submit review</button></form></div>
  </section>
  <aside className="space-y-4"><div className="rounded-2xl border border-indigo-400/15 bg-indigo-400/[0.05] p-5"><p className="text-xs uppercase tracking-[0.16em] text-indigo-300">Contract</p><p className="mt-3 text-3xl font-semibold">₹{project.totalAmount.toLocaleString("en-IN")}</p><p className="mt-1 text-xs text-white/30">Total project value</p><div className="mt-6 rounded-xl border border-white/[0.07] bg-black/20 p-4"><p className="text-xs text-white/30">Escrow</p><p className="mt-1 text-sm font-medium capitalize text-emerald-300">{project.escrowStatus.replace(/-/g," ")}</p></div>{project.escrowStatus==="not-funded"&&<button onClick={fund} className="mt-4 w-full rounded-xl bg-white py-3 text-xs font-semibold text-black">Fund & start project</button>}{project.status!=="completed"&&project.escrowStatus!=="not-funded"&&<button onClick={complete} className="mt-3 w-full rounded-xl border border-white/[0.09] py-3 text-xs text-white/60">Mark project completed</button>}{message&&<p className="mt-3 text-xs text-emerald-300">{message}</p>}</div><Link href="/messages" className="block rounded-2xl border border-white/[0.08] bg-white/[0.025] p-5 hover:bg-white/[0.04]"><p className="text-xs text-white/30">Project communication</p><h3 className="mt-2 font-medium">Open messages →</h3><p className="mt-2 text-sm text-white/35">Talk directly with the other side of the project.</p></Link></aside>
 </div></AppShell>
}
